version: "3.9"

networks:
  net_bernard_betest:   

services:
  betest-app:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_INITDB_DATABASE: db_bernard_betest
    depends_on:
      - mongo
      - redis
    networks:
      - net_bernard_betest

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - dbvol:/data/db
    ports:
      - 27017:27017
    networks:
      - net_bernard_betest

  redis:
    image: redis:latest
    container_name: redis_bernard_betest
    restart: always
    ports: 
      - 6379:6379
    networks:
      - net_bernard_betest

volumes:
 dbvol: